const {test}=require('node:test'); const assert=require('node:assert/strict'); const vm=require('node:vm'); const fs=require('node:fs');
const source=fs.readFileSync(require('node:path').join(__dirname,'../src/taskpane/taskpane.js'),'utf8');
const save=source.substring(source.indexOf('async function saveMetadata()'),source.indexOf('function validateRequiredMetadata()'));
function setup(locked=false) {
 const events=[];const ctx={intakeMode:true,isSaving:false,currentDriveItem:{name:'Old.pdf'},currentListItem:{id:'1'},currentDocumentUrl:'url',dorkSite:{id:'s'},dorkDocumentsLibrary:{id:'l'},window:{sessionStorage:{}},document:{getElementById:id=>id==='title'?{value:'New'}:{disabled:false}},console,
 setSaveStatus(){},validateRequiredMetadata(){},buildDesiredFilename:()=> 'New.pdf',materializeNewTags:async()=>{},resolvePeople:async()=>{},resolveDesiredContentType:async()=>null,buildSharePointFormValues:()=>[],assertIntakeFileClosed:async()=>{events.push('closed');if(locked)throw Error('locked');},requestNumbering:async()=>{events.push('reserve');return null;},validateUpdateListItem:async v=>events.push(v[0]?.FieldName==='FileLeafRef'?'rename':'metadata'),verifySavedMetadata:async()=>events.push('verify'),rememberDocumentLocation(){},refreshIntakeFiles:async()=>events.push('list'),renderIntakeFiles(){},getErrorMessage:e=>e.message};
 vm.runInNewContext(save+'\nglobalThis.save=saveMetadata;',ctx);return {ctx,events};
}
test('GEEK saves and verifies PDF metadata without an Office host or document writes',async()=>{const {ctx,events}=setup();await ctx.save();assert.deepEqual(events,['closed','reserve','metadata','verify','rename','verify','list']);});
test('An open file cannot allocate a number or write metadata through intake',async()=>{const {ctx,events}=setup(true);ctx.console={error(){}};await ctx.save();assert.deepEqual(events,['closed']);});
test('Intake loading and selection contain no numbering or Office writes',()=>{const block=source.split('/* BROWSER INTAKE:')[1];assert.doesNotMatch(block,/requestNumbering|saveHostDocument|syncHostMetadata|Office\./);});
test('Intake preserves arbitrary extensions and extensionless files',()=>{const block=source.substring(source.indexOf('function buildDesiredFilename()'),source.indexOf('async function verifySavedMetadata('));for(const name of ['x.pdf','x.png','x']){const ctx={intakeMode:true,currentDriveItem:{name},document:{getElementById:()=>({value:'Updated'})},getFieldValue:()=> 'Old'};vm.runInNewContext(block+'\nglobalThis.filename=buildDesiredFilename;',ctx);assert.equal(ctx.filename(),'Updated'+(name.includes('.')?name.slice(name.lastIndexOf('.')):''));}});
