const {test}=require('node:test');const assert=require('node:assert/strict');
const {TermManager,label}=require('../src/terms/service');
function setup(terms=[],post=async()=>({id:'new',labels:[{name:'New',isDefault:true}]})) {
 const writes=[];const manager=new TermManager(async(url,options)=>{
  if(options){writes.push(JSON.parse(options.body));return post();}
  if(url.endsWith('/groups'))return {value:[{id:'group',displayName:'DORK'}]};
  if(url.endsWith('/sets'))return {value:[{id:'c',localizedNames:[{name:'Collection'}]},{id:'s',localizedNames:[{name:'System / Platform'}]},{id:'domain',localizedNames:[{name:'Domain'}]}]};
  if(url.includes('/terms/'))return {value:[]};return {value:terms};
 },'host,site,web');return{manager,writes};
}
test('only the two approved DORK sets can be written',async()=>{const {manager,writes}=setup();await manager.initialize();await assert.rejects(manager.create('domain','New',''),/Choose/);assert.equal(writes.length,0);await manager.create('collection','  New   School Year  ','Annual startup');assert.deepEqual(writes[0],{labels:[{name:'New School Year',languageTag:'en-US',isDefault:true}],descriptions:[{description:'Annual startup',languageTag:'en-US'}]});});
test('aliases and whitespace/case variants block duplicate writes after fresh read',async()=>{const {manager,writes}=setup([{id:'one',labels:[{name:'Microsoft 365',isDefault:true},{name:'M365'}]}]);await manager.initialize();await assert.rejects(manager.create('system',' m365 ','notes'),/Already exists: Microsoft 365/);await assert.rejects(manager.create('system','MICROSOFT   365',''),/Already exists/);assert.equal(writes.length,0);});
test('nested terms participate in duplicate checks',async()=>{let writes=0;const manager=new TermManager(async(url,options)=>{if(options){writes++;return{};}return {value:url.endsWith('/sets/c/children')?[{id:'parent',labels:[{name:'Parent'}]}]:url.endsWith('/terms/parent/children')?[{id:'child',labels:[{name:'Child'}]}]:[]};},'site');manager.sets.collection='c';await assert.rejects(manager.create('collection','child',''),/Already exists/);assert.equal(writes,0);});
test('paging accepts encoded site IDs but rejects foreign origins and loops',async()=>{const manager=new TermManager(async url=>url.includes('page=2')?{value:[{id:2}]}:{value:[{id:1}],'@odata.nextLink':'https://graph.microsoft.com/v1.0/sites/host,site,web/termStore/groups?page=2'},'host,site,web');assert.equal((await manager.all(manager.base+'/groups')).length,2);manager.request=async()=>({value:[],'@odata.nextLink':'https://evil.test/'});await assert.rejects(manager.all(manager.base+'/groups'),/Unexpected/);manager.request=async url=>({value:[],'@odata.nextLink':url});await assert.rejects(manager.all(manager.base+'/groups'),/Unexpected/);});
test('server permission and uncertain-write errors do not report success or retry writes',async()=>{for(const status of [403,409,500]){let attempts=0;const {manager}=setup([],async()=>{attempts++;throw Object.assign(Error('server'),{status});});await manager.initialize();await assert.rejects(manager.create('collection','New',''),status===403?/permission/:status===409?/someone else/:/could not be confirmed/);assert.equal(attempts,1);}});
