const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const Module=require('node:module');const ts=require('typescript');
const cache={};function source(name){if(cache[name])return cache[name].exports;const file=path.resolve(__dirname,'../src/webparts/dorkDashboard',name+'.ts');const m=new Module(file,module);cache[name]=m;m.paths=module.paths;const normal=m.require.bind(m);m.require=n=>n==='@microsoft/sp-webpart-base'?{BaseClientSideWebPart:class{}}:n==='@microsoft/sp-http'?{SPHttpClient:{configurations:{v1:{}}}}:n.endsWith('.css')?{}:n.startsWith('./')?source(n.slice(2)):normal(n);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2017}}).outputText,file);return m.exports;}
const model=source('model');const {classify}=source('classification');const {allRows,loadData}=source('data');
const doc=(review,lifecycle='Active')=>({id:'DORK-0001',title:'A',url:'',domain:'',fn:'',type:'',owner:'',modified:'',review,lifecycle});
test('review status: past, today, inclusive 30-day boundary, healthy, missing and inactive',()=>{
 const today='2026-10-02';assert.equal(model.reviewStatus(doc('2026-10-01'),today),'Past review date');assert.equal(model.reviewStatus(doc(today),today),'Due today / approaching');assert.equal(model.reviewStatus(doc('2026-11-01'),today),'Due today / approaching');assert.equal(model.reviewStatus(doc('2026-11-02'),today),'Good standing');assert.equal(model.reviewStatus(doc(''),today),'Missing review date');assert.equal(model.reviewStatus(doc('2026-02-30'),today),'Missing review date');assert.equal(model.reviewStatus(doc('2020-01-01','Draft'),today),'Not active');assert.equal(model.reviewCounts([doc('','Draft')],today).reduce((n,r)=>n+r.count,0),0);
});
test('lifecycles preserve unexpected choices and missing values',()=>{const counts=model.lifecycleCounts([doc('','draft'),doc('','Active'),doc('','Approved'),doc('','')]);assert.equal(counts.find(c=>c.label==='Draft').count,1);assert.equal(counts.find(c=>c.label==='Approved').count,1);assert.equal(counts.find(c=>c.label==='Missing lifecycle').count,1);});
test('calendar excludes inactive reviews and closed needs without shifting date-only fields',()=>{const n={title:'Need',target:'2026-10-23T00:00:00Z',url:'',status:'New'};const events=model.calendarEvents([doc('2026-10-23T00:00:00Z'),doc('2026-10-23','Draft')],[n,{...n,status:'Completed'},{...n,status:'Cancelled'}]);assert.equal(events.length,2);assert.ok(events.every(ev=>ev.date==='2026-10-23'));});
test('classification considers task and keeps agreed Voice and iPad mappings',()=>{assert.ok(classify('Genesis accounts').some(c=>c.domain==='IDENTITY'&&c.fn==='Account Management'));assert.ok(classify('phone extension').some(c=>c.domain==='NETWORK'&&c.fn==='Voice'));assert.ok(classify('IEP iPad').some(c=>c.domain==='ENDPOINT'&&c.fn==='iPad'));assert.ok(classify('VM recovery').some(c=>c.domain==='CYBERSECURITY'&&c.fn==='Restoration'));assert.deepEqual(classify('Genesis'),[]);assert.deepEqual(classify('<script>unknownword</script>'),[]);});
test('copyable URLs encode literal filename punctuation and reject foreign origins',()=>{const site='https://example.sharepoint.com/sites/DORK';const url=model.fileUrl('/sites/DORK/Shared Documents/A & B #1%2.docx',site);assert.equal(new URL(url).hash,'');assert.ok(url.endsWith('/A%20%26%20B%20%231%252.docx'));assert.equal(model.safeUrl('https://evil.test/file',site),'');assert.equal(model.safeUrl('javascript:alert(1)',site),'');assert.equal(model.escapeHtml('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;');});
test('REST pagination includes all pages and rejects loops/foreign next links',async()=>{const site='https://example.sharepoint.com/sites/DORK',url=site+'/_api/items';let reads=0;assert.deepEqual(await allRows(url,async()=>++reads===1?{value:[{Id:1}],'odata.nextLink':url+'?page=2'}:{value:[{Id:2}]},site),[{Id:1},{Id:2}]);await assert.rejects(allRows(url,async()=>({value:[],'odata.nextLink':url}),site),/repeated/);await assert.rejects(allRows(url,async()=>({value:[],'odata.nextLink':'https://evil.test/_api/'}),site),/Unexpected/);});
test('loading failures remain errors instead of reporting healthy zero counts',async()=>{const data=await loadData('https://example.sharepoint.com/sites/DORK',async()=>{throw Error('403');});assert.equal(data.documentError,'403');assert.equal(data.needsError,'403');});
test('dashboard interactions filter register, classify, select calendar day and expose URL copy fallback',async()=>{
 const {JSDOM}=require('jsdom');const dom=new JSDOM('<div id="app"></div>',{url:'https://example.sharepoint.com/sites/DORK'});
 const app=new (source('DorkDashboardWebPart').default)();app.domElement=dom.window.document.getElementById('app');app.data={documents:[{...doc('2026-10-23'),title:'Document & reference',url:'https://example.sharepoint.com/sites/DORK/Shared%20Documents/A%20%26%20B.docx'}],needs:[{id:1,title:'Phone extension',priority:'Normal',status:'New',assigned:'Tech',target:'2026-10-23',url:'',details:'',kind:'Procedure',assignedId:1}],documentError:'',needsError:'',documentsUrl:'',needsUrl:'',newNeedUrl:'',loadedAt:new Date()};app.month='2026-10';app.draw();
 assert.equal(app.domElement.querySelector('tbody tr').textContent.includes('Document & reference'),true);
 const search=app.domElement.querySelector('[data-search]');search.value='phone extension';search.dispatchEvent(new dom.window.Event('input'));assert.match(app.domElement.querySelector('[data-results]').textContent,/NETWORK → Voice/);
 app.domElement.querySelector('[data-date="2026-10-23"]').click();assert.match(app.domElement.querySelector('.agenda').textContent,/Phone extension/);assert.match(app.domElement.querySelector('.agenda').textContent,/DORK-0001/);
 app.domElement.querySelector('[data-filter="Draft"]').click();assert.match(app.domElement.querySelector('tbody').textContent,/No documents match/);app.domElement.querySelector('[data-clear]').click();assert.equal(app.domElement.querySelector('input[readonly]').value,app.data.documents[0].url);
 await app.copy(app.domElement.querySelector('[data-copy]'));assert.match(app.domElement.querySelector('.copyStatus').textContent,/Link selected/);assert.equal(app.domElement.querySelector('input[readonly]').selectionStart,0);
 app.onDispose();assert.equal(app.domElement.innerHTML,'');
});
test('data loader discovers columns, ignores unnumbered uploads and preserves dates and encoded paths',async()=>{
 const site='https://example.sharepoint.com/sites/DORK';const cols=['DORK ID','Domain','Function','Document Type','Owner','Lifecycle','Next Review','Details','Need Type','Priority','Status','Assigned To','Target Date'];const read=async url=>{
 if(url.includes('TaxonomyHiddenList'))return {value:[{Id:15,Term:'NETWORK'},{Id:31,Term:'NETWORK:Voice'},{Id:3,Term:'Procedure'}]};
 if(url.includes('/fields?'))return {value:cols.map((Title,i)=>({Title,InternalName:'F'+i}))};
 if(url.includes('/lists?'))return {value:[{Id:'42841641-0241-4e53-99f3-2ecb68ed1d9e',Title:'Documentation Needs',DefaultViewUrl:'/sites/DORK/Lists/Needs',DefaultNewFormUrl:'/sites/DORK/Lists/Needs/NewForm.aspx',DefaultDisplayFormUrl:'/sites/DORK/Lists/Needs/DispForm.aspx'}]};
 if(url.includes("dd8ac8ef"))return {value:[{Id:1,FSObjType:0,F0:'DORK-0001',Title:'A',FileRef:'/sites/DORK/Shared Documents/A #1.docx',F4:{Title:'Owner'},F5:'Active',F6:'2026-10-23T00:00:00Z',FieldValuesAsText:{F1:'15',F2:'31',F3:'3',F4:'6'}},{Id:2,FSObjType:0,Title:'Not numbered'}]};
 return {value:[{Id:1,Title:'Need',F7:'Details',F8:'Procedure',F9:'High',F10:'New',F12:'2026-10-23T00:00:00Z',F11:{Title:'Tech'},FieldValuesAsText:{F11:'4'},F11Id:4}]};
 };
 const data=await loadData(site,read);assert.equal(data.documentError,'');assert.equal(data.needsError,'');assert.equal(data.documents.length,1);assert.equal(data.documents[0].fn,'Voice');assert.equal(data.documents[0].domain,'NETWORK');assert.equal(data.documents[0].owner,'Owner');assert.match(data.documents[0].url,/%231.docx$/);assert.equal(data.documents[0].review,'2026-10-23T00:00:00Z');assert.equal(data.needs[0].assigned,'Tech');assert.match(data.needs[0].url,/ID=1$/);
});
